### ISSUE TITLE
Create Docker Swarm out of ATTX containerised stack

### ISSUE THREAD

**Issue by jkesanie** [ATTX-project/platform-deployment#19]
#### Description

Create docker swarm compose file v3 and customised based on ATTX stack components.

 #### DoD
Generated v3 docker compose file and running in docker swarm mode cluster.

#### Testing
Peer-review

**Comment by joasilva** [comment]
Dcompose 0.9.0 isn't available from Gradle Plugins yet (cf: https://plugins.gradle.org/plugin/com.chrisgahlert.gradle-dcompose-plugin):


FAILURE: Build failed with an exception.

* Where:
Build file '/tmp/test-dcompose/build.gradle' line: 2

* What went wrong:
Plugin [id: 'com.chrisgahlert.gradle-dcompose-plugin', version: '0.9.0'] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Gradle Central Plugin Repository (plugin 'com.chrisgahlert.gradle-dcompose-plugin' has no version '0.9.0' - see https://plugins.gradle.org/plugin/com.chrisgahlert.gradle-dcompose-plugin for available versions)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

**Comment by joasilva** [comment]
With the new Dcompose 0.9.0 it's possible to generate a v3 docker-compose.yml, and deploy it in Docker Swarm (Vagrant cluster or cPouta). However, troubleshooting is still needed because the application stack doesn't work as expected because the "links" tag is ignored:


cloud-user@attx-swarm-1:~/provision-swarm$ docker stack deploy attx-stack --compose-file docker-compose.yml 
**Ignoring unsupported options: links**

Creating network attx-stack_default
Creating service attx-stack_fuseki
Creating service attx-stack_virtuoso
Creating service attx-stack_gm-api
Creating service attx-stack_elasticsearch-siren
Creating service attx-stack_frontend
Creating service attx-stack_wfapi
Creating service attx-stack_mysql
Creating service attx-stack_shared
Creating service attx-stack_uv-dpus
Creating service attx-stack_attx-dpus
Creating service attx-stack_elasticsearch5
Creating service attx-stack_backend
cloud-user@attx-swarm-1:~/provision-swarm$ docker service ls
ID            NAME                            MODE        REPLICAS  IMAGE
0uk2jhv8y28w  attx-stack_elasticsearch5       replicated  0/1       elasticsearch:5.1.2
14lf2m9o4j3l  attx-stack_mysql                replicated  0/1       tenforce/unified-views-mariadb:latest
8duzo7ryeopf  attx-stack_virtuoso             replicated  0/1       tenforce/virtuoso:virtuoso-v7.2.0-latest
f5g031mtkv2y  attx-stack_fuseki               replicated  0/1       attxproject/attx-fuseki:latest
io002w3khuxe  attx-stack_gm-api               replicated  0/1       attxproject/gm-api:latest
j0skvigk6ge3  attx-stack_shared               replicated  0/1       attxproject/uv-attx-shared:latest
ky1683nrnmcj  attx-stack_attx-dpus            replicated  0/1       attxproject/uv-attx-dpus:latest
pjzi8mkvvcy1  attx-stack_frontend             replicated  0/1       tenforce/unified-views-frontend:latest
rztnllk1rx46  attx-stack_uv-dpus              replicated  0/1       tenforce/unified-views-add-dpus:latest
sphu8b3irp32  attx-stack_elasticsearch-siren  replicated  0/1       attxproject/elasticsearch:latest
w6vhizso88ao  attx-stack_wfapi                replicated  0/1       attxproject/wf-api:latest
xkemlsurf883  attx-stack_backend              replicated  0/1       tenforce/unified-views-backend:latest

**Comment by joasilva** [comment]
Finally got UnifiedViews working:
```{docker}
version: '3'                                                                            
services:                                                                               
                                                                                        
  attx-dpus:                                                                            
    image: attxproject/uv-attx-dpus:latest                                              
    networks:                                                                           
      - attx                                                                            
                                                                                        
  backend:                                                                              
    image: tenforce/unified-views-backend:latest                                        
    volumes:                                                                            
      - shared_config:/config                                                           
      - shared_dpu:/unified-views/dpu                                                   
      - shared_lib:/unified-views/lib                                                   
    networks:                                                                           
      - attx                                                                            
    depends_on:                                                                         
      - shared                                                                          
      - mysql                                                                           
    deploy:                                                                             
      placement:                                                                        
        constraints: [node.role == manager]                                             
                                                                                        
  frontend:                                                                             
    image: tenforce/unified-views-frontend:latest                                       
    volumes:                                                                            
      - shared_config:/config                                                           
      - shared_dpu:/unified-views/dpu                                                   
      - shared_lib:/unified-views/lib                                                   
    ports:                                                                              
    - 8080:8080                                                                         
    networks:                                                                           
      - attx                                                                            
    depends_on:                                                                         
      - shared                                                                          
      - backend                                                                         
    deploy:                                                                             
      placement:                                                                        
        constraints: [node.role == manager]                                             
                                                                                        
  mysql:                                                                                
    image: tenforce/unified-views-mariadb:feat-compact-modular                          
    environment:                                                                        
    - MYSQL_ROOT_PASSWORD=iamroot!                                                      
    networks:                                                                           
      - attx                                                                            
    deploy:                                                                             
      placement:                                                                        
        constraints: [node.role == manager]                                             
                                                                                        
  shared:                                                                               
    image: tenforce/unified-views-shared                                                
    volumes:                                                                            
      - shared_config:/config                                                           
      - shared_dpu:/unified-views/dpu                                                   
      - shared_lib:/unified-views/lib                                                   
    networks:                                                                           
      - attx                                                                            
    deploy:                                                                             
      placement:                                                                        
        constraints: [node.role == manager]

networks:                                                                               
  attx:                                                                                 
    driver: "overlay"                                                                   
                                                                                        
volumes:                                                                                
  shared_config:                                                                        
  shared_dpu:                                                                           
  shared_lib:
```

**Comment by joasilva** [comment]
UnifiedViews now running in Swarm mode (5-node swarm) at Cpouta, reachable @http://86.50.169.160:8080/unifiedviews/, give your IP address to João (FW rules).

**Comment by joasilva** [comment]
Provisioning files uploaded to https://github.com/ATTX-project/platform-deployment/tree/feature-swarm-mode ("swarm-mode-cpouta" and "swarm-mode-vagrant" folders).
