### ISSUE TITLE
User guide (v1)

### ISSUE THREAD

**Issue by jkesanie** [ATTX-project/platform-deployment#34]
#### Description
After installing the platform, user needs to implement his data brokering scenario. 
- What are different DPUs? and how to use them?
- Examples with actual data
- Screencasts?

#### DoD
Public document

#### Testing
Pasi or Pauli has tests instructions.

**Comment by blankdots** [comment]
Issue that came up:
* https://github.com/ATTX-project/workflow-component/issues/45
* https://github.com/ATTX-project/graph-component/issues/24
* We cleaned the prov graph and now we are not doing it  - We need to think about the repercussions of that change

User Guide started at: https://github.com/ATTX-project/project-management/wiki/User-guide

**Comment by jkesanie** [comment]
Rough cut:
https://github.com/ATTX-project/ATTX-project.github.io/blob/dev/Import/attx_project/User-guide.md

**Comment by blankdots** [comment]
Review part 1 (language and formatting):

Please see rephrased and spellchecked proposal with comparison to the previous version at: https://github.com/ATTX-project/ATTX-project.github.io/commit/570ebdc19f8567405d3bda52913dd81a1daf90b5#diff-f66636df82a5216b8042a7e91899a18c

Instead of ATTX platform I propose we should start using the ATTX Semantic Broker (mostly because that is for ELAG) or ATTX Semantic Broker platform, and when talking about the components we should use either ATTX components or ATTX (software) stack, _platform_ is a bit too general.

From the User guide there is a lot of emphasis on DPU(s) term, most likely a user should not concern him/her-self with what that is, but just with the fact that it is a UI component/interface.

When reading the guide (from a software architecture) perspective it seems like we are selecting the technology before describing what it (the ATTX Semantic Broker) does, or how it works. I think there should be just a mention (if necessary) about the fact that it is a UnifiedViews DPU (more precisely the details of the implementation of the UI).

Thus I propose we change a bit the language regarding how we describe the UI components, from DPU to either component or service or functionality etc. (personal bias I do prefer: service).

also when working with OAI-PMH harvester not sure how the _modified records_ in the output will look like or what they will consist of?

The images might need to be referenced differently in the source (the relative path might need to be to the position of the generated HTML in the root directory) ... needs testing!!!

To follow part 2.

**Comment by jkesanie** [comment]
I think that the platform -> semantic broker is a good call. 
While we are using UnifiedViews, I think we can talk about DPUs. What should be added though is small introduction to what DPU actually means (i.e. basic building block of pipelines). 

Details of the DPUs (for example content of the modified records) will be added as the implementation progresses.

**Comment by blankdots** [comment]
Review part 2 (content):

(Understanding that some content has yet to be added or finalised) We might want to offer more details or address the issues:
* From reading this guide users might be confronted with an unfamiliarity of the UnifiedViews UI, therefore to the current user guide learning curve, there is an added dependency of familiarising to the UnifiedViews UI, maybe we should link to it and mentioning as a requirement - reason why also the suggestion of using the DPU term as little as possible;
* in the Complete example - of some of the configurations that were used to execute the pipelines;
* the fact that provenance information that is collected and exposed and it is query-ready at specific endpoints by (application) clients and users ?;
* JSON-LD Framing based RDF to JSON Mapper - not entirely sure how this should work (it seems it has similar description as Custom RDF to JSON mapper). The input should also consist of a JSON-LD frame and the output should be a JSON document based on the JSON-LD frame (meaning the GM-API will take the configuration and process the dataset URIs accordingly);
* figure X - typo ?
* added "In the case two external datasets are used in the Processing pipeline with distinct licenses, the license associated with the derived dataset will be the most restrictive." in order to address this issue;
* "Target graph is generated based on the contextual information." - a bit unclear on how this might be implemented as we also expose the Default graph which contains all the named graphs in the store;
* why does the Publish to API have a dataset metadata input and Publish to file not ? We can also add the metadata in a *.txt file or even in the RDF with the data;
* "Every pipeline essentially represents one or more datasets." are these generated dataset or input data source or both ? We assume this information should be available in the provenance information ?;
* File download DPU does it also take into consideration the fact the the download might happen via an API which requires a token ?;
* Describe External Data source or Describe data set DPU is not really a Transformer type of DPU by their functionality or their result (which is ingested in the graph - so it is mostly of extractor type - as it extracts information from the user) ?.

**Comment by jkesanie** [comment]
""Every pipeline essentially represents one or more datasets." are these generated dataset or input data source or both ? We assume this information should be available in the provenance information ?;"

I was referring to generated/updated working data set.

"Describe External Data source or Describe data set DPU is not really a Transformer type of DPU by their functionality or their result (which is ingested in the graph - so it is mostly of extractor type - as it extracts information from the user) ?."

These things can be tricky =) I categorized everything that creates new data as transformer. Describe DPUs add provenance related data to the store.

**Comment by blankdots** [comment]
@jkesanie just another thought it seems, that this will make some of the existing pages obsolete, we may want to followup and mark the pages that are obsolete e.g. https://attx-project.github.io/ETL-Artifacts.html
