### ISSUE TITLE
Replicate running Semantic Broker on Kontena

### ISSUE THREAD

**Issue by blankdots** [ATTX-project/platform-deployment#45]
#### Description
Try basic feature of Kontena by deploying version 1.0 images with the platform.
#### DoD
Kontena yml files.
#### Testing
Peer Review

**Comment by joasilva** [comment]
All components deployed and running in Kontena Cloud, except for UnifiedViews Frontend and Backend, whose status is "Initialised" instead of "Running".

Troubleshooting:
- This might be to the fact that UV Frontend and Backend can't read their properties from volume containers (such as "shared"). Kontena recommends creating volumes and running them with `local` driver and `stack` scope instead;
- Some Kontena issues might display sucessfuly deployed services as "initialised" instead of "running" (cf. https://github.com/kontena/kontena/issues/2290 https://github.com/kontena/kontena/issues/2310)
